<a href="https://colab.research.google.com/github/atanugiri/DL-exercises/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch
# Create random tensor
random_tensor = torch.rand(size=(7,7))
random_tensor


tensor([[0.4691, 0.2408, 0.1210, 0.2930, 0.9008, 0.3222, 0.2432],
        [0.7919, 0.5903, 0.8013, 0.8794, 0.6660, 0.8749, 0.6118],
        [0.5870, 0.0114, 0.0589, 0.5796, 0.6072, 0.4103, 0.0419],
        [0.6060, 0.0171, 0.0070, 0.4210, 0.5029, 0.3489, 0.5492],
        [0.5406, 0.0523, 0.1537, 0.5351, 0.5866, 0.0088, 0.8905],
        [0.1274, 0.2015, 0.2839, 0.3581, 0.1601, 0.0452, 0.3505],
        [0.8194, 0.5289, 0.8744, 0.2484, 0.2795, 0.0645, 0.3972]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
random_tensor_2 = torch.rand(size=(1,7))
# Perform matrix multiplication
matrix_multiplication = torch.matmul(random_tensor, random_tensor_2.T)
matrix_multiplication

tensor([[1.0346],
        [2.1318],
        [0.8471],
        [0.8628],
        [0.9088],
        [0.5460],
        [1.6733]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor = torch.rand(size=(7,7))
random_tensor
random_tensor_2 = torch.rand(size=(1,7))
random_tensor_2
# Matrix multiply tensors
matrix_multiplication = torch.matmul(random_tensor, random_tensor_2.T)
matrix_multiplication, matrix_multiplication.device


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 device(type='cpu'))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
device

# Create two random tensors on GPU
r_t_1 = torch.rand(size = (2,3)).to(device)
print(f"r_t_1: \n{r_t_1}")

r_t_2 = torch.rand(size = (2,3)).to(device)
print(f"r_t_2: \n{r_t_2}")


r_t_1: 
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
r_t_2: 
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
mm = torch.mm(r_t_1, r_t_2.T)
mm, mm.dtype, mm.device

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.float32,
 device(type='cuda', index=0))

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
mm_max = torch.max(mm)
mm_max
# Find min
mm_min = torch.min(mm)
mm_min


tensor(0.3647, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(f"max id = {torch.argmax(mm)}")

# Find arg min
print(f"min id = {torch.argmin(mm)}")

max id = 3
min id = 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)
# Create random tensor
tensor_A = torch.rand(size = (1,1,1,10))
tensor_A

# Remove single dimensions
torch.squeeze(tensor_A)

# Print out tensors and their shapes
print(f"{tensor_A}\n {tensor_A.shape}")

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
 torch.Size([1, 1, 1, 10])
